// File generated by FlutterFire CLI.
// Run: flutterfire configure
// Replace the placeholder values below with your actual Firebase project config.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) return web;
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions not supported for this platform.',
        );
    }
  }

  // Replace all values below with your Firebase project values.
  // Get them from: Firebase Console → Project Settings → Your apps

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'YOUR_ANDROID_API_KEY',
    appId: '1:000000000000:android:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'kinoflow-YOUR_PROJECT_ID',
    storageBucket: 'kinoflow-YOUR_PROJECT_ID.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'YOUR_IOS_API_KEY',
    appId: '1:000000000000:ios:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'kinoflow-YOUR_PROJECT_ID',
    storageBucket: 'kinoflow-YOUR_PROJECT_ID.appspot.com',
    iosBundleId: 'com.dhanush.kinoflow',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'YOUR_WEB_API_KEY',
    appId: '1:000000000000:web:0000000000000000',
    messagingSenderId: '000000000000',
    projectId: 'kinoflow-YOUR_PROJECT_ID',
    storageBucket: 'kinoflow-YOUR_PROJECT_ID.appspot.com',
    authDomain: 'kinoflow-YOUR_PROJECT_ID.firebaseapp.com',
  );
}
